In [1]:
import numpy as np

In [2]:
tensor_2d = np.array([(1, 2, 3, 4),
                      (4, 5, 6, 7),
                      (8, 9, 10, 11),
                      (12, 13, 14, 15)
                     ])

In [3]:
print(tensor_2d)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
print(tensor_2d[3][3])

15


In [5]:
print(tensor_2d[0:2, 0:2])

[[1 2]
 [4 5]]


In [6]:
import tensorflow as tf

In [7]:
tf.compat.v1.disable_eager_execution()

In [8]:
tf_tensor = tf.convert_to_tensor(tensor_2d, dtype = tf.float64)

In [9]:
with tf.compat.v1.Session() as sess:
    print(sess.run(tf_tensor))

[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [ ]:
# MobileNet

# https://github.com/Zehaos/MobileNet


# 하이퍼 파라미터

# 레이어 수, 노드 수

# 활성화 함수(ReLu, Sigmoid, ...)

# 옵티마이저(GD, SGD, Adam, ...)

# 학습률(0.001, 0.01, ...)

# 학습 횟수(epoch 수, 비용함수의 오차)

# loss 함수



# Softmax 여러가지 값의 합을 1로 만듬

# One-hot Encoding(제일 높은 값을 1로 만듬)


# categorical_crossentropy (두 개 분포 사이의 거리를 계산하는 방법)